import Header from "@/components/Header";
import UserHero from "@/components/users/UserHero";

import React from "react";
import Head from "next/head";
import useUser from "@/hooks/useUser";
import { useRouter } from "next/router";
import { ClipLoader } from "react-spinners";

const UserView = () => {
  const router = useRouter();
  const { userId } = router.query;

  const { data: fetchedUser, isLoading } = useUser(userId as string);

  //   if (isLoading || !fetchedUser) {
  //     return (
  //       <div
  //         className="
  //                 flex
  //                 h-full
  //                 items-center
  //                 justify-center
  //             "
  //       >
  //         <ClipLoader color="lightblue" size={80} />
  //       </div>
  //     );
  //   }

  return (
    <>
      <Head>
        <title>
          {!fetchedUser
            ? `User Profile - Twitter`
            : `${fetchedUser?.name} - Profile`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter_icon.ico" />
      </Head>
      {(isLoading || !fetchedUser) && (
        <div
          className="
          flex
          h-full
          items-center
          justify-center
          "
        >
          <ClipLoader color="lightblue" size={80} />
        </div>
      )}
      <Header showBackArrow label={fetchedUser?.name} />
      <UserHero userId={userId as string} />
    </>
  );
};

export default UserView;
